##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/atril
    - caja
    - djvulibre
    - gcc
    - git
    - gobject-introspection
    - intltool
    - itstool
    - libgxps
    - make
    - mate-common
    - poppler-glib
    - texlive-bin
    - webkit2gtk
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - git
    - gobject-introspection
    - intltool
    - libcaja-extension-dev
    - libdjvulibre-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgxps-dev
    - libkpathsea-dev
    - libpoppler-glib-dev
    - libsecret-1-dev
    - libsm-dev
    - libspectre-dev
    - libtiff-dev
    - libwebkit2gtk-4.0-dev
    - libx11-dev
    - libxml2-dev
    - lsb-release
    - make
    - mate-common
    - xsltproc
    - yelp-tools
    - zlib1g-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/atril.git
    - cairo-gobject-devel
    - caja-devel
    - desktop-file-utils
    - djvulibre-devel
    - gcc
    - gcc-c++
    - git
    - gobject-introspection-devel
    - gtk3-devel
    - libXt-devel
    - libglade2-devel
    - libgxps-devel
    - libjpeg-turbo-devel
    - libsecret-devel
    - libspectre-devel
    - libtiff-devel
    - make
    - mate-common
    - poppler-glib-devel
    - redhat-rpm-config
    - texlive-lib-devel
    - webkitgtk4-devel
    - yelp-tools

  ubuntu:
    - git
    - gobject-introspection
    - intltool
    - libcaja-extension-dev
    - libdjvulibre-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgxps-dev
    - libkpathsea-dev
    - libpoppler-glib-dev
    - libsecret-1-dev
    - libsm-dev
    - libspectre-dev
    - libtiff-dev
    - libwebkit2gtk-4.0-dev
    - libx11-dev
    - libxml2-dev
    - lsb-release
    - make
    - mate-common
    - xsltproc
    - yelp-tools
    - zlib1g-dev

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: atril-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
